default to stub int10 implementation on arm
There should be no reason to need a real int10 implementation on arm,
and switching to stub is an easy way to fix:

  xf86x86emu.c: In function 'xf86Int10ExecSetup':
  xf86x86emu.c:56:9: error: unknown field 'xf_outb' specified in initializer
  xf86x86emu.c:57:9: error: unknown field 'xf_outw' specified in initializer
  xf86x86emu.c:58:9: error: unknown field 'xf_outl' specified in initializer

which is caused by the following in compiler.h:

  #define outb xf_outb
  #define outw xf_outw
  #define outl xf_outl

Signed-off-by: Rob Clark <robdclark@gmail.com>
Acked-by: Daniel Stone <daniels@collabora.com>