hw/xwin: Remove obsolete redundant declarations of winPushPixels()
winPushPixels() and winpushpxl.c was removed in it's entirety in commit
f31bd087e8a7f65cd588bd1d022bb18e72b2a60c "Death to mfb"

wingc.c:37:1: error: redundant redeclaration of ‘winPushPixels’
win.h:1104:1: note: previous declaration of ‘winPushPixels’ was here

Signed-off-by: Jon TURNEY <jon.turney@dronecode.org.uk>
Reviewed-by: Colin Harrison <colin.harrison@virgin.net>