XQuartz: Fix build failure due to incorrect PseudoramiXExtensionInit prototype
pseudoramiX.c:129:1: error: conflicting types for 'PseudoramiXExtensionInit' [Semantic Issue]
PseudoramiXExtensionInit(int argc, char *argv[])
^
../../include/extinit.h:175:13: note: previous declaration is here
extern void PseudoramiXExtensionInit(void);
            ^

Signed-off-by: Jeremy Huddleston <jeremyhu@apple.com>