config: conftest needs an include directive to locate X11/Xfuncproto.h
The compiler option -fvisibility=hidden is erroneously missing
due to a faulty configuration test. The gcc command is unable to
locate X11/Xfuncproto.h unless the build occurs on a
system where X11 development headers are installed.

configure:21294: checking for symbol visibility support
configure:21323: gcc -std=gnu99 -c -g -O2 -fvisibility=hidden  conftest.c >&5
conftest.c:144:28: fatal error: X11/Xfuncproto.h: No such file or directory

The solution is to add an include directive to obtain the location
of X11/Xfuncproto.h which may or may not be the system installed headers.

Reviewed-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Signed-off-by: Gaetan Nadon <memsize@videotron.ca>
Signed-off-by: Keith Packard <keithp@keithp.com>